# Generated by Django 4.2.7 on 2025-11-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bp_reminder_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive reminders to take BP readings"
                    ),
                ),
                (
                    "bp_reminder_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("twice_weekly", "Twice Weekly"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                        ],
                        default="daily",
                        help_text="Frequency of BP reminders",
                        max_length=20,
                    ),
                ),
                (
                    "bp_reminder_time",
                    models.TimeField(
                        default="09:00",
                        help_text="Preferred time for BP reminders (24-hour format)",
                    ),
                ),
                (
                    "medication_reminder_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive reminders for medications"
                    ),
                ),
                (
                    "insight_notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive notifications for new insights"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("bp_reminder", "BP Reading Reminder"),
                            ("medication_reminder", "Medication Reminder"),
                            ("insight", "New Insight"),
                            ("system", "System Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("sent_successfully", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-sent_at"],
                        name="notificatio_user_id_7495e7_idx",
                    )
                ],
            },
        ),
    ]
