# Generated by Django 4.2.7 on 2025-11-05 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the medication", max_length=200
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Dosage (e.g., '10mg', '1 tablet')", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "Once Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("three_times_daily", "Three Times Daily"),
                            ("four_times_daily", "Four Times Daily"),
                            ("as_needed", "As Needed"),
                            ("weekly", "Weekly"),
                            ("other", "Other"),
                        ],
                        default="once_daily",
                        help_text="Frequency (e.g., 'Once daily', 'Twice daily', 'As needed')",
                        max_length=50,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Date when medication was started"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when medication was stopped (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this medication is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the medication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(help_text="When the medication was taken"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(
                        fields=["medication", "-taken_at"],
                        name="medications_medicat_76e218_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["user", "-is_active"], name="medications_user_id_e70be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["user", "-start_date"], name="medications_user_id_7fc09d_idx"
            ),
        ),
    ]
