# Generated by Django 4.2.7 on 2025-11-05 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodPressureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(help_text="Systolic pressure (top number)"),
                ),
                (
                    "diastolic",
                    models.IntegerField(help_text="Diastolic pressure (bottom number)"),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, help_text="Heart rate in BPM", null=True
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(help_text="When the reading was taken"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional notes or context"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-recorded_at"],
                        name="readings_bl_user_id_8cd26f_idx",
                    )
                ],
            },
        ),
    ]
