# Generated by Django 4.2.7 on 2025-11-05 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_text",
                    models.TextField(help_text="The generated insight message"),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend Analysis"),
                            ("anomaly", "Anomaly Detection"),
                            ("correlation", "Correlation Analysis"),
                            ("alert", "Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-generated_at"],
                        name="insights_us_user_id_24ba97_idx",
                    )
                ],
            },
        ),
    ]
